channels:
- conda-forge
- defaults
dependencies:
- pip
- pip:
  - finufft==2.2.0
- dask
- distributed
- h5py
- matplotlib
- numba
- numpy
- pandas
- pyyaml
- requests
- scipy
- sympy
- tqdm
name: mosaic
